/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-blue': '#4F46E5',
        'secondary-teal': '#14B8A6',
        'accent-coral': '#FB7185',
        'base-white': '#FFFFFF',
        'soft-gray': '#F8FAFC',
        'light-blue': '#EFF6FF',
        'subtle-lavender': '#F5F3FF',
        'level1-bg': '#DBEAFE',
        'level1-border': '#3B82F6',
        'level1-text': '#1E3A8A',
        'level2-bg': '#D1FAE5',
        'level2-border': '#10B981',
        'level2-text': '#065F46',
        'level3-bg': '#E9D5FF',
        'level3-border': '#A855F7',
        'level3-text': '#6B21A8',
        'level4-bg': '#FED7AA',
        'level4-border': '#F97316',
        'level4-text': '#9A3412',
        'success': '#22C55E',
        'warning': '#FBBF24',
        'error': '#EF4444',
        'info': '#06B6D4',
        'price-tag': '#DC2626',
        'original-price': '#9CA3AF',
        'in-stock': '#059669',
        'sale-badge': '#EA580C',
        'premium': '#7C3AED',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#94A3B8',
        'text-link': '#2563EB',
        'bg-color': '#FFFFFF',
        'text-color': '#0F172A',
        'card-bg': '#FFFFFF',
      },
      boxShadow: {
        'custom': '0 4px 24px 0 var(--shadow)',
      },
    },
  },
  plugins: [],
  safelist: []

};
